--- # This play books will show hoe to use include and call multiple roles stuff

# discrete play will be divided into each part based on each action
# and the main discrete_plays.yml will call all the required play using include module
#

- hosts: node2
  user: prasanth
  become: yes
  connection: ssh
  gather_facts: no
  vars_files:
   - DiscretePlays/vars/vars.yml
  tasks:
   - import_tasks: DiscretePlays/packages/packages.yml
   - import_tasks: DiscretePlays/command/commands.yml
  handlers:
   - import_tasks: DiscretePlays/handlers/handlers.yml
