--- # This playbook show you how to ignore some now issues during the play

- hosts: node2
  user: prasanth
  connection: ssh
  become: yes
  gather_facts: no
  vars:
   playbook_version: IGNORE_ERRORS-1.0
  vars_files:
   - conf/copyrights.yml
   - conf/webdefaults.yml
  tasks:
  - name: Execute a command that will fail
    command: /bin/false
    ignore_errors: yes
  - name: install telnet
    yum: pkg=telnet state=latest
