--- # This Play Books will run loops for the given taks

- hosts: node2
  user: prasanth
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Creating below Users on given server.
    user: name={{ item }} state=present
    with_items:
    - test_user1
    - test_user2
    - test_user3
