--- # Using Step argument will run each task if yes is given to prompt

# ansible-playbook step_into.yml --step then it will prompt fot each task with yes,no,continue
- hosts: node2
  user: prasanth
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: telnet
    tags: telnetI
    yum: pkg=telnet state=latest
  - name: lynx
    tags: lynxI
    yum: pkg=lynx state=latest
  - name: list home
    tags: listHome
    command: ls -al /home/prasanth/
    register: results
  - debug: var=results
