--- # This Playbook will take extra arguments form cmd and pass those to playbook

- hosts: '{{ host }}'
  user: '{{ user }}'
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing PKG {{ pkg }}
    yum: pkg={{ pkg }} state=latest
