--- # Using wait_for for some process to come up

- hosts: node2
  user: prasanth
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install Tomcat Server
    action: yum name=tomcat state=latest
  - name: Waiting for Tomcat to start on port 8080
    wait_for:
        port: 8080
        state: started
  - name: Verify Lynx Installation
    action: yum name=lynx state=present
