---

- hosts: local
  user: prasanth
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1a
  vars_files:
    - conf/copyright.yml
    - conf/apache_common.yml
  vars_prompt:
    - name: Web_Domain
      prompt: Web Domain
