---

- hosts: local
  user: prasanth
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1a
  vars_files:
    - conf/copyright.yml
    - conf/apache_common.yml
  vars_prompt:
    - name: Web_Domain
      prompt: Web Domain
  tasks:
  - name: Installing Lynx Web Browser
    action: yum name=lynx state=installed
  - name: Check the Telnet Pkg Installed or Not
    action: yum name=telnet state=absent
